[Example] ggml: add multimodel example with CI
second-state/WasmEdge-WASINN-examples pull request #111
Opened 2024-03-08 02:27 UTC by dm4

2024-03-08 02:27 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-03-08 05:07 UTC, hydai requested changes
Let's use tinyllama + llava instead, to show that we can handle not only the chat model but also the image model.

2024-03-11 03:05 UTC, dm4 commented
> Let's use tinyllama + llava instead, to show that we can handle not only the chat model but also the image model.

Given that the performance of the tinyllama model is unsatisfactory, I will attempt to use the llava and llama2 models for this example.

2024-03-11 12:13 UTC, hydai approved these changes

2024-03-11 12:14 UTC, merged