[Example] ggml: add nnrpc example for RPC usage
second-state/WasmEdge-WASINN-examples pull request #119
Opened 2024-03-19 02:56 UTC by dm4

2024-03-19 02:56 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-03-19 18:06 UTC, hydai requested changes

2024-03-19 18:06 UTC, hydai commented on wasmedge-ggml/nnrpc/README.md
> +# Llava Example For WASI-NN with GGML Backend
The name is wrong.

2024-03-20 04:49 UTC, dm4 commented on wasmedge-ggml/nnrpc/README.md
> +# Llava Example For WASI-NN with GGML Backend
Fixed

2024-03-20 04:52 UTC, hydai approved these changes

2024-03-20 05:16 UTC, merged