Add Qwen.cpp example
second-state/WasmEdge-WASINN-examples pull request #137
Opened 2024-04-28 13:29 UTC by jokemanfire

Add a Qwen model example.

2024-04-28 13:29 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-04-30 10:20 UTC, hydai requested changes

2024-04-30 10:20 UTC, hydai commented on wasmedge-ggml/qwen/src/main.rs
> +use serde_json::json;
Please use `cargo fmt` and `cargo clippy` to re-format the rust code.

2024-05-03 05:39 UTC, hydai approved these changes
Thanks.

2024-05-10 01:58 UTC, merged