[Example] use local image in all demos
second-state/WasmEdge-WASINN-examples pull request #16
Opened 2022-12-28 04:02 UTC by gusye1234

Signed-off-by: Jianbai Ye <jianbaiye@outlook.com>

2022-12-28 04:04 UTC, hydai requested changes
What's the license of these photos? Is it acceptable to put them into our source tree?

2022-12-28 04:04 UTC, hydai commented on .gitignore
> +# openvino-mobilenet-image/input.jpg
Please remove these lines directly.

2022-12-28 04:09 UTC, gusye1234 commented
The license for those two images is [here](https://github.com/bytecodealliance/wasi-nn/blob/main/rust/examples/images/LICENSE), which is the same as this repo

2022-12-28 04:11 UTC, hydai commented
> The license for those two images is [here](https://github.com/bytecodealliance/wasi-nn/blob/main/rust/examples/images/LICENSE), which is the same as this repo

Putting a link to identify the source of these photos is better.

2023-03-02 08:00 UTC, hydai commented
Hi @gusye1234 
Could you add a link to the original image? I will merge this once the link and license information is done.

2023-03-02 08:30 UTC, hydai approved these changes

2023-03-02 08:31 UTC, gusye1234 commented
Add the links and licenses in readme

2023-03-02 08:31 UTC, merged

2023-03-02 08:31 UTC, hydai commented
Thanks!