Give an example of llama tflite
second-state/WasmEdge-WASINN-examples pull request #165
Opened 2024-12-19 15:21 UTC by victoryang00

working with wamr.

2024-12-19 15:22 UTC, juntao commented
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-12-19 16:28 UTC, hydai requested changes
I got a little confused. The title of this PR said it plans to add a new example for Llama TFLite. However, the `README.md` and `Cargo.toml` are all about MobileNet. Could you please check if the README and metadata are correct?

2024-12-20 04:29 UTC, victoryang00 commented
fixed

2024-12-24 11:29 UTC, hydai approved these changes

2024-12-24 11:29 UTC, merged