Demo mobilenet image
second-state/WasmEdge-WASINN-examples pull request #2
Opened 2022-06-30 11:51 UTC by gusye1234

2022-07-05 12:56 UTC, q82419 requested changes
Please rebase to the lastest master.

2022-07-05 15:58 UTC, gusye1234 commented on examples/mobilenet/.gitignore
> +mobilenet.bin
But if user uses this demo, it will download fixtures under this dir, and mess git's tracking.

2022-07-06 21:53 UTC, q82419 commented on examples/mobilenet/.gitignore
> +mobilenet.bin
It's user's responsibility to not to mess the source directory. After all, we'll not approve the PR with garbage files.

2022-07-06 22:04 UTC, q82419 requested changes

2022-07-06 22:04 UTC, q82419 commented on examples/mobilenet_image/download_mobilenet.sh
> +    wget --no-clobber --directory-prefix=$TODIR https://raw.githubusercontent.com/radu-matei/wasi-nn-guest/main/rust/images/1.jpg -O input.jpg
Use the original one: 
https://github.com/bytecodealliance/wasi-nn/tree/main/rust/images
Not to use the forked one.

2022-07-06 22:04 UTC, q82419 commented on examples/mobilenet_image/README.md
> +![](https://raw.githubusercontent.com/radu-matei/wasi-nn-guest/main/rust/images/1.jpg)
Use the original one:
https://github.com/bytecodealliance/wasi-nn/tree/main/rust/images
Not to use the forked one.

2022-07-11 13:15 UTC, q82419 requested changes

2022-07-11 13:15 UTC, q82419 commented on .gitignore
> +openvino-mobilenet-image/input.jpg
Need to add `openvino-mobilenet-raw/` ?

2022-07-11 13:19 UTC, gusye1234 commented on .gitignore
> +openvino-mobilenet-image/input.jpg
OK

2022-07-11 13:42 UTC, q82419 approved these changes

2022-07-11 13:43 UTC, merged