[feat] New example `CodeLlama-13B-Instruct`
second-state/WasmEdge-WASINN-examples pull request #54
Opened 2023-10-23 09:42 UTC by apepkuss

2023-10-23 09:42 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-10-23 10:01 UTC, apepkuss commented
@hydai Could you please help review this PR? Thanks a lot!

2023-10-23 15:25 UTC, hydai requested changes

2023-10-23 15:25 UTC, hydai commented on wasmedge-ggml-codellama/Cargo.toml
> +wasi-nn = { git = "https://github.com/second-state/wasmedge-wasi-nn", branch = "dm4/ggml" }
Use `"ggml"` instead.

2023-10-26 08:01 UTC, apepkuss commented on wasmedge-ggml-codellama/Cargo.toml
> +wasi-nn = { git = "https://github.com/second-state/wasmedge-wasi-nn", branch = "dm4/ggml" }
Fixed. Thanks!

2023-10-26 08:20 UTC, apepkuss commented
@hydai The review issue has been fixed. Please help review the changes. Thanks a lot!

2023-10-26 08:22 UTC, hydai approved these changes

2023-10-26 08:33 UTC, merged